[package]
name = "blogrs"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
actix-web = "4.1.0"
serde = {version = "1.0.143", features = ["derive"]}
serde_json = "1.0.83"
json = "0.12.4"
